### ISSUE TITLE
The path of the uploaded upgrade file update.zip is incorrect

### ISSUE THREAD

**Issue by ali2liu** [T-REX-XP/RRManager#1]
![屏幕截图 2024-03-14 084047](https://github.com/T-REX-XP/RRManager/assets/28823482/8e605446-8159-4a9d-9e8e-b06e55bf00c3)

there are two "//"

**Comment by T-REX-XP** [comment]
Hi. Fixed. Just check out 1.0.25 version

**Comment by fishredleung** [comment]
still  not working , even though the path contain the update.zip ,  the app still could not resolve it
