### ISSUE TITLE
v.2.0.2 The interface is blank

### ISSUE THREAD

**Issue by andy094** [T-REX-XP/RRManager#11]
After installing version 2.02, even after clearing the configuration, the installation interface remains blank, as shown in the picture
![Uploading 24B7D53A27269A8D5452A40375348377.png…]()

**Comment by andy094** [comment]
![24B7D53A27269A8D5452A40375348377](https://github.com/T-REX-XP/RRManager/assets/44518878/9d32a3ad-c980-41af-97f0-99adf904a156)

**Comment by wenjiamian** [comment]
> Known issue. Please check the latest version. 2.0.6. RR manager is under the active development.

Can't find it, where can I download it? 2.0-4 also has this issue

**Comment by T-REX-XP** [comment]
Please check the latest release - https://github.com/T-REX-XP/RRManager/releases/tag/v.2.0.11
