### ISSUE TITLE
Language change switch

### ISSUE THREAD

**Issue by MoeBai** [T-REX-XP/RRManager#13]
Hey Bro! I find that the rr author commit the language pack for this project.I can`t find the switch to change the lanugage from enu to chs.

**Comment by T-REX-XP** [comment]
Already fixed in the - https://github.com/T-REX-XP/RRManager/releases/tag/v.2.0.12. You can improve the translations by modifying the files - https://github.com/T-REX-XP/RRManager/tree/v.2.0.12/src/app/texts .
Just switch the DSM version.
