### ISSUE TITLE
N100-DSM7.2-s6400无法安装RRmanager插件

### ISSUE THREAD

**Issue by MrLee980** [T-REX-XP/RRManager#19]
![image](https://github.com/T-REX-XP/RRManager/assets/128470614/4598a43a-315b-405f-9b36-2d1775116e15)
![image](https://github.com/T-REX-XP/RRManager/assets/128470614/23ebcb7f-ed37-43bf-81c9-59ee88f82cc4)
![image](https://github.com/T-REX-XP/RRManager/assets/128470614/d895fc2c-a8ee-4c56-9ed7-a4eac6577e9c)

**Comment by nodis** [comment]
我也是这样，DSM 7.2

**Comment by sumingyd** [comment]
相同问题

**Comment by qq1468332374** [comment]
一样一样，求解决

**Comment by MrLee980** [comment]
> > 同样一样，求解决
> 
> 去安装2.0-19成功，但是无法使用，一直在加载中

2.0.19我也无法安装成功，不管是git下spk还是矿神源里安装都失败
