### ISSUE TITLE
Fix localization rus

### ISSUE THREAD

**Issue by molthun** [T-REX-XP/RRManager#24]
src/app/texts/rus/strings localization language is not correct.
this is not Russian, this is Ukrainian, and there is no translation to Russian yet. leave this file empty.
Transfer this translation to Ukrainian.
![photo_2024-04-19_17-22-09](https://github.com/T-REX-XP/RRManager/assets/47332561/724c3468-a45a-4c41-8551-14b4538b0cf3)

**Comment by sqehrzed** [comment]
https://github.com/T-REX-XP/RRManager/pull/26 Fixed

**Comment by T-REX-XP** [comment]
Russian language is not supported by RRM.
