### ISSUE TITLE
“Adddon”界面无法添加插件

### ISSUE THREAD

**Issue by TokamakB** [T-REX-XP/RRManager#3]
![image](https://github.com/T-REX-XP/RRManager/assets/109128677/a9def802-d2b4-4a68-8ee8-4a4eb0c57569)
原来我没添加“setrootpw”插件，后面的方框内没打勾，再次点击方框打勾以后，点击“save addons changes”保存以后，点击右下脚的刷新。

![image](https://github.com/T-REX-XP/RRManager/assets/109128677/e300adfe-22a9-4d66-aeba-6758e673632f)
又恢复了没勾选的状态。

**Comment by wjz304** [comment]
这是正常的，插件的改变不会立即生效，保存以后需要重启编译才会生效。
This is normal. Changes to the plug-in will not take effect immediately. You need to restart compilation after saving to take effect.

**Comment by T-REX-XP** [comment]
As I mentioned in the readme , that feature is still in progress. 80% is done, but I need to apply selected addons to the rr config. It's in my TODO list. I will update you soon.

**Comment by T-REX-XP** [comment]
fixed in the release 34.
