### ISSUE TITLE
After installing rr-manger(2.0.19), clicking the icon results in an error (in chrome console).

### ISSUE THREAD

**Issue by que01** [T-REX-XP/RRManager#36]
DSM version: DSM 7.2.1-69057 Update 5
rr version: 24.6.5

the error in chrome devtools:
<img width="509" alt="image" src="https://github.com/T-REX-XP/RRManager/assets/5241691/32ecc6b1-ab0c-4448-9f1e-97c7cb1f5df9">

i try to debug the error, find the function _getRrConfig in __checkDownloadFolder will read localStorage, by the key  "rrConfig". But chrome devtool cant find it in localStorage Item.

<img width="591" alt="image" src="https://github.com/T-REX-XP/RRManager/assets/5241691/59163661-3790-4b9e-bbad-b8d0927f402e">

**Comment by T-REX-XP** [comment]
Please use the latest version. It must be more stable.
