### ISSUE TITLE
It keeps prompting that the folder does not exist, and you need to restart the suite after creating a new folder.

### ISSUE THREAD

**Issue by primovist** [T-REX-XP/RRManager#4]
In fact, the folder is an existing folder.
![image](https://github.com/T-REX-XP/RRManager/assets/2242315/91433863-28bd-4903-8a00-b0898b503606)

**Comment by T-REX-XP** [comment]
Please check out the latest release. It must be already resolved.

**Comment by fishredleung** [comment]
> Please check out the latest release. It must be already resolved.

It can not resolve case sensitive folder name and it can not reach the /tmp sub folder after uploading the update.zip file
