### ISSUE TITLE
Unable to install RRManager v.2.0.64 alongside WEB Station

### ISSUE THREAD

**Issue by Spelvi** [T-REX-XP/RRManager#43]
Hello, if you have WEB Station RRManager installed, it cannot be installed, leaving the installation broken.

**Comment by PrestarLin** [comment]
yes,DS918+ rr2.8.4 iam also. @T-REX-XP

**Comment by niko44** [comment]
+1 it seems that there is a conflit between WebStation and RRManager.

 1/ If I only stop Webstation's service, it's the same, ==> impossible to install RRManager. 

 2/ If I uninstall Webstation, then install RRManager 2.0.64 ==> install is ok but UI of RRManager still show a spinner. 

 3/ If I uninstall Webstation, then install RRManager 2.0.64, then reinstall WebStation ==>same as 2/

**Comment by T-REX-XP** [comment]
Sorry guys. I have no glue what is the issue with Web Station package. It's in my pipeline yet.

**Comment by duckeaty** [comment]
the same, but the 2.0-36 is ok.

**Comment by T-REX-XP** [comment]
Fixed conflict with WebStation in the latest release - [v.2.0.74](https://github.com/T-REX-XP/RRManager/releases/tag/v.2.0.74)

**Comment by Spelvi** [comment]
> Fixed conflict with WebStation in the latest release - [v.2.0.74](https://github.com/T-REX-XP/RRManager/releases/tag/v.2.0.74)

Thank you very much for your great work, champ.
