### ISSUE TITLE
Cannot install v.2.0.68 

### ISSUE THREAD

**Issue by doandat943** [T-REX-XP/RRManager#48]
i using version [v.2.0.19](https://github.com/T-REX-XP/RRManager/releases/tag/v.2.0.19) before, try update but it show below error.
I have try uninstall old version and install new version but it keep show this error

<img width="1252" alt="{28564826-6FC0-498E-B19F-94A4D06CEB44}" src="https://github.com/user-attachments/assets/e2408ca5-dd2c-4f9d-b491-bfdc768f65a8">

**Comment by yanggqi** [comment]
和Web Station冲突，删掉就可以装了。
如果Web Station有用，最高可以安装到2.0.36

**Comment by doandat943** [comment]
Thank, uninstall Web Station and install RR-Manager successful

**Comment by Jetzow527** [comment]
> 和Web Station冲突，删掉就可以装了。 如果Web Station有用，最高可以安装到2.0.36

原来是这样啊...我说我的71怎么一直安装不上去。
