### ISSUE TITLE
远程访问 图标显示不全 内存单位不对？

### ISSUE THREAD

**Issue by schnuffell** [T-REX-XP/RRManager#5]
[![pFRZ0N8.png](https://s21.ax1x.com/2024/03/18/pFRZ0N8.png)](https://imgse.com/i/pFRZ0N8)

**Comment by T-REX-XP** [comment]
Actually the icons are emojis. So, the look and feel are related to the your OS and fonts that are available.
The system info are taking from the Syno API. But, I will double check.

**Comment by T-REX-XP** [comment]
The wrong RAM size fixed in the latest release - https://github.com/T-REX-XP/RRManager/releases/tag/v.2.0.11
