### ISSUE TITLE
Health condition judgment error and file upload update error

### ISSUE THREAD

**Issue by halfpreschooler** [T-REX-XP/RRManager#52]
let rr_health_status = rrConf.rr_health == 'health' ? this.TYPE_NORMAL : this.TYPE_ATTENTION;
Need to be modified to
let rr_health_status = rrConf.rr_health == 'healthy' ? this.TYPE_NORMAL : this.TYPE_ATTENTION;

The helper in uploadFileDialog.js is not updateHelper,
self.helper.updateFileInfoHandler
Need to be modified to
self.parent.updateHelper.updateFileInfoHandler

**Comment by T-REX-XP** [comment]
Already fixed in the new release [v.2.0.75](https://github.com/T-REX-XP/RRManager/releases/tag/v.2.0.75)
