### ISSUE TITLE
Error. TypeError: self.hideProgressIndicator is not a function

### ISSUE THREAD

**Issue by CodeFishK** [T-REX-XP/RRManager#55]
Upload File From DiskStation Alert
Error. TypeError: self.hideProgressIndicator is not a function

**Comment by PlanetSider** [comment]
同样问题

**Comment by T-REX-XP** [comment]
Fixed in the new release [v.2.0.75](https://github.com/T-REX-XP/RRManager/releases/tag/v.2.0.75)
