### ISSUE TITLE
v2.0-74 want reboot during any time

### ISSUE THREAD

**Issue by Kaelber** [T-REX-XP/RRManager#56]
I have installed the current RR Loader as OVA in a VM-Manager and the DSM itself runs well. If I install the RR Manager after all confirmations and reboots etc. I see in the widget of DSM in the right side that message "Your RR is waiting for a reboot." But if I reboot again, nothing changes.

![grafik](https://github.com/user-attachments/assets/6208d91e-dfce-4b5a-a742-061abc06f362)

![grafik](https://github.com/user-attachments/assets/23d5b34e-55d3-4848-bc3f-2e8c2419c653)

**Comment by wjz304** [comment]
似乎有什么判断没有生效

**Comment by T-REX-XP** [comment]
Fixed in the new release: [v.2.0.75](https://github.com/T-REX-XP/RRManager/releases/tag/v.2.0.75)
