### ISSUE TITLE
RR已升级24.11.0最新版，打开RRM还是提示升级上一版24.10.3。

### ISSUE THREAD

**Issue by aliyy2021** [T-REX-XP/RRManager#59]
![{0A2829CD-E4E7-4741-8EF4-32C3DBC08742}](https://github.com/user-attachments/assets/387998b3-4eba-4551-877f-893f1954280e)
RR已升级24.11.0最新版，打开RRM还是提示升级上一版24.10.3。

**Comment by MaverickXie** [comment]
你是怎么升级到24.11.0版本的？是通过RRM升级的吗？

**Comment by aliyy2021** [comment]
> 你是怎么升级到24.11.0版本的？是通过RRM升级的吗？

RRM升级提示找不到文件，我启动到RR控制台升级的

**Comment by MaverickXie** [comment]
可以试试把群晖计划任务中与RRM相关的四个脚本都删除后再重新安装RRM
