### ISSUE TITLE
 No such file or directory: '/volume2/rr/tmp/update.zip'

### ISSUE THREAD

**Issue by wenjiamian** [T-REX-XP/RRManager#6]
上传updae.zip文件后确认更新报错：Unable to update RR: [Errno 2] No such file or directory:
'/volume2/rr/tmp/update.zip'. Please upload the file and try againe
<img width="1247" alt="image" src="https://github.com/T-REX-XP/RRManager/assets/34673454/a883922a-97a2-4671-98c4-206578e86119">
原因分析：rrmanager安装在存储空间1，自动在存储空间1创建了/rr/tmp共享目录，上传update文件正常上传到/rr/tmp。确认更新的时候却去读取存储空间2了，截图的/volume2/，所以文件不存在。手动把自动创建的/rr/tmp迁移到存储空间2就正常了

**Comment by T-REX-XP** [comment]
Could you please check out the latest release - https://github.com/T-REX-XP/RRManager/releases/tag/v.2.0.11 ?
