### ISSUE TITLE
v.2.0.79 No_log_available is displayed under addons and empty settings.

### ISSUE THREAD

**Issue by eragon4k** [T-REX-XP/RRManager#62]
No_log_available is displayed under addons in v.2.0.79 with rr24.11.11.
Empty settings in v.2.0.79 with rr24.11.11.

**Comment by bilibili20001** [comment]
The same issue
![20241119170603](https://github.com/user-attachments/assets/993d3985-d89d-4258-bd9a-8bce9e2a78f3)
![20241119170611](https://github.com/user-attachments/assets/505516c7-afb5-4b0d-aefb-8fe00a9a74f7)

**Comment by wjz304** [comment]
RR v24.11.11 has bug.

Temporary solution:
Please execute the following command as root in DSM shell (or through task plan):
sed -i 's/synoboo\$/synoboot\$/' /usr/bin/rr-loaderdisk.sh

**Comment by xooxl** [comment]
> RR v24.11.11 has bug.
> 
> Temporary solution: Please execute the following command as root in DSM shell (or through task plan): sed -i 's/synoboo$/synoboot$/' /usr/bin/rr-loaderdisk.sh

the same issue, but this workaround not work. 

1. ssh to the DSM;
2. sudo -i
3. sed -i 's/synoboo$/synoboot$/' /usr/bin/rr-loaderdisk.sh
4. reboot
5. RR manager still show "no log avaiable ".

**Comment by wjz304** [comment]
> > RR v24.11.11 has bug.
> > Temporary solution: Please execute the following command as root in DSM shell (or through task plan): sed -i 's/synoboo$/synoboot$/' /usr/bin/rr-loaderdisk.sh
> 
> the same issue, but this workaround not work.
> 
> 1. ssh to the DSM;
> 2. sudo -i
> 3. sed -i 's/synoboo$/synoboot$/' /usr/bin/rr-loaderdisk.sh
> 4. reboot
> 5. RR manager still show "no log avaiable ".

No restarting.

**Comment by xooxl** [comment]
> sed -i 's/synoboo$/synoboot$/' /usr/bin/rr-loaderdisk.sh

try again follow step:
1. ssh to the DSM;
2. sudo -i
3. sed -i 's/synoboo$/synoboot$/' /usr/bin/rr-loaderdisk.sh
4. RR manager still show "no log avaiable ".

failed again.

**Comment by wjz304** [comment]
> > sed -i 's/synoboo$/synoboot$/' /usr/bin/rr-loaderdisk.sh
> 
> try again follow step:
> 
> 1. ssh to the DSM;
> 2. sudo -i
> 3. sed -i 's/synoboo$/synoboot$/' /usr/bin/rr-loaderdisk.sh
> 4. RR manager still show "no log avaiable ".
> 
> failed again.

You should just take a break and wait for the update.

**Comment by xooxl** [comment]
> > > sed -i 's/synoboo$/synoboot$/' /usr/bin/rr-loaderdisk.sh
> > 
> > 
> > try again follow step:
> > 
> > 1. ssh to the DSM;
> > 2. sudo -i
> > 3. sed -i 's/synoboo$/synoboot$/' /usr/bin/rr-loaderdisk.sh
> > 4. RR manager still show "no log avaiable ".
> > 
> > failed again.
> 
> You should just take a break and wait for the update.

Thanx, i found the problem. the replace command should be:
sed -i 's/synoboo\$/synoboot\$/' /usr/bin/rr-loaderdisk.sh

OK, fixed.

**Comment by cnhz76** [comment]
> > > > sed -i 's/synoboo$/synoboot$/' /usr/bin/rr-loaderdisk.sh
> > > 
> > > 
> > > try again follow step:
> > > 
> > > 1. ssh to the DSM;
> > > 2. sudo -i
> > > 3. sed -i 's/synoboo$/synoboot$/' /usr/bin/rr-loaderdisk.sh
> > > 4. RR manager still show "no log avaiable ".
> > > 
> > > failed again.
> > 
> > 
> > You should just take a break and wait for the update.
> 
> Thanx, i found the problem. the replace command should be: sed -i 's/synoboo\$/synoboot\$/' /usr/bin/rr-loaderdisk.sh
> 
> OK, fixed.

Thanx！

**Comment by yyciticnet** [comment]
Use the following command 
`sed -i 's/synoboo\$/synoboot\$/' /usr/bin/rr-loaderdisk.sh` 

Fixed the following problem :

ERRno2 .....No such...  '/tmp/rr_update_progress'

**Comment by MiSA-205** [comment]
> Use the following command `sed -i 's/synoboo\$/synoboot\$/' /usr/bin/rr-loaderdisk.sh`

Thank you, fix my the problem! 👍🙏✅
