### ISSUE TITLE
Update error with 24.11.12 + 2.0.79

### ISSUE THREAD

**Issue by eragon4k** [T-REX-XP/RRManager#66]
![Screenshot 2024-11-23 123735](https://github.com/user-attachments/assets/8702f3ab-fa91-46c5-95cd-0040830a7def)

**Comment by eragon4k** [comment]
v2.0.19 works just fine and is stable.

**Comment by MaverickXie** [comment]
Agree, me too

**Comment by LIUBANGJIAN** [comment]
是不同人开发者吗？

**Comment by eragon4k** [comment]
> Are they developed by different people?

It appears to be the same developer(@yuriiNazarenkoTine).

**Comment by undosh77** [comment]
关于 24.11.11 RRM 异常问题

临时对策：
请在 DSM shell 中 以 root 方式执行以下命令 （或者通过 任务计划）：
sed -i 's/synoboo\$/synoboot\$/' /usr/bin/rr-loaderdisk.sh

----

About 24.11.11 RRM abnormality

Temporary solution:
Please execute the following command as root in DSM shell (or through task plan):
sed -i 's/synoboo\$/synoboot\$/' /usr/bin/rr-loaderdisk.sh

**Comment by eragon4k** [comment]
Try this and update to 24.11.12

About 24.11.11 RRM abnormality
Temporary solution:
Please execute the following command as root in DSM shell (or through task plan):
sed -i 's/synoboo\$/synoboot\$/' /usr/bin/rr-loaderdisk.sh
