### ISSUE TITLE
v.2.0.79   rr manager  RR 24.12.1 升级到 RR 24.12.3失败

### ISSUE THREAD

**Issue by gexiaopeng** [T-REX-XP/RRManager#72]
rr manager 版本 v.2.0.79   ，从  RR 24.12.1 升级到 RR 24.12.3失败
![1](https://github.com/user-attachments/assets/2e5bf6f2-7eb4-43cf-8f5b-963b17ccc4d6)
![2](https://github.com/user-attachments/assets/1fee6c8f-2ee5-4067-94f0-e772856890fd)

**Comment by eragon4k** [comment]
Try this and update to 24.11.12

About 24.11.11 RRM abnormality
Temporary solution:
Please execute the following command as root in DSM shell (or through task plan):
`sed -i 's/synoboo\$/synoboot\$/' /usr/bin/rr-loaderdisk.sh`

[https://github.com/T-REX-XP/RRManager/issues/66](url)
